name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: swift:5.3-focal
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - id: file_changes
      uses: trilom/file-changes-action@v1.2.3
      with:
        output: ' '
    - id: pre_commit_action
      uses: pre-commit/action@v2.0.0
      with:
        extra_args: downstream --files ${{ steps.file_changes.outputs.files}}; echo "hello world"
    - uses: daohoangson/comment-on-github@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: ${{ join(steps.run_tests.outputs.*, '\n') }}
