name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - name: Get changed files
      id: changes
      # Set outputs using the command.
      run: |
        echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
    - id: pre_commit_action
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: downstream --files ${{ steps.changes.outputs.all }};
        extra_args: downstream-docker --files ${{ steps.changes.outputs.all }};
    - id: get_changes
      run: |
        content="$(swift run downstream -o human ${{ steps.changes.outputs.all }})"
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=test::$content"
    - uses: daohoangson/comment-on-github@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: ${{ steps.get_changes.outputs.test }}
