name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - run: if [ ! -f "/etc/lsb-release" ] ; then echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release; fi
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
